name: Test ApiDOM Validator

on:
  push:
    branches:
      - main
      - trigger-error-option

  workflow_dispatch:
    branches:
      - main
      - trigger-error-option

jobs:
  test_github_action:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.test1.outcome }}
      output2: ${{ steps.test2.outcome }}
      output3: ${{ steps.test3.outcome }}
      output4: ${{ steps.test4.outcome }}

    steps:
      - uses: actions/checkout@v2

      - name: "Test 1: Validate openapi.json file at Severity level 1 (Errors)"
        id: test1
        continue-on-error: true
        uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi.json
          fails-on: 1
      - name: "Test 2: Validate openapi.json file at Severity level 4 (Hints)"
        id: test2
        continue-on-error: true
        uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi.json
          fails-on: 4
      - name: "Test 3: Validate openapi_with_errors.json file at Severity level 1 (Errors)"
        id: test3
        continue-on-error: true
        uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi_with_errors.json
          fails-on: 1
      - name: "Test 4: Validate openapi_with_errors.json file at Severity level 4 (Hints)"
        id: test4
        continue-on-error: true
        uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi_with_errors.json
          fails-on: 4

  verify_outcomes:
    needs: test_github_action
    runs-on: ubuntu-latest
    
    steps:
      - name: Expected outcomes
        run: |
          echo " Test |     Definition File      | Fails On Level | Expected Outcome | Actual Outcome"
          echo "------|--------------------------|----------------|------------------|----------------"
          echo "  1   |       openapi.json       |        1       |      success     |      ${{ needs.test_github_action.outputs['output1'] }}"
          echo "  2   |       openapi.json       |        4       |      failure     |      ${{ needs.test_github_action.outputs['output2'] }}"
          echo "  3   | openapi_with_errors.json |        1       |      failure     |      ${{ needs.test_github_action.outputs['output3'] }}"
          echo "  4   | openapi_with_errors.json |        4       |      failure     |      ${{ needs.test_github_action.outputs['output4'] }}"

          if [ "${{ needs.test_github_action.outputs['output1'] }}" == "success" ] && [ "${{ needs.test_github_action.outputs['output2'] }}" == "failure" ] && [ "${{ needs.test_github_action.outputs['output3'] }}" == "failure" ] && [ "${{ needs.test_github_action.outputs['output4'] }}" == "failure" ]; then
            echo "Test succeeded: Actual outcomes match expected outcomes"
            exit 0
          else
            echo "Test failed: Actual outcomes do not match expected outcomes."
            exit 1
          fi
   
