name: Test ApiDOM Validator

on:
  push:
    branches:
      - main

  workflow_dispatch:
    branches:
      - main
      - trigger-error-option

jobs:
  test_github_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi.json


