name: Test ApiDOM Validator

on:
  push:
    branches:
      - main
      - trigger-error-option

  workflow_dispatch:
    branches:
      - main
      - trigger-error-option

jobs:
  test_github_action:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.openapi-1.outcome }}
      output2: ${{ steps.openapi-4.outcome }}
      output3: ${{ steps.openapiWithErrors-1.outcome }}
      output4: ${{ steps.openapiWithErrors-4.outcome }}

    steps:
      - uses: actions/checkout@v2

      - name: Validate openapi.json file at Severity level 1 (Errors)
        id: openapi-1
        continue-on-error: true
        uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi.json
          fails-on: 1
      - name: Validate openapi.json file at Severity level 4 (Hints)
        id: openapi-4
        continue-on-error: true
        uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi.json
          fails-on: 4
      - name: Validate openapi_with_errors.json file at Severity level 1 (Errors)
        id: openapiWithErrors-1
        continue-on-error: true
        uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi_with_errors.json
          fails-on: 1
      - name: Validate openapi_with_errors.json file at Severity level 4 (Hints)
        id: openapiWithErrors-4
        continue-on-error: true
        uses: amandalian/apidom-validate@trigger-error-option
        with:
          definition-file: ./.github/workflows/fixtures/openapi_with_errors.json
          fails-on: 4

  verify_outcomes:
    needs: test_github_action
    runs-on: ubuntu-latest
    
    steps:
      - name: Expected outcomes
        run: |
          echo "Expected Outcome | Actual Outcome"
          echo "-----------------|----------------"
          echo "     Success     | ${{ needs.test_github_action.outputs['output1'] }}"
          echo "     Failure     | ${{ needs.test_github_action.outputs['output2'] }}"
          echo "     Failure     | ${{ needs.test_github_action.outputs['output3'] }}"
          echo "     Failure     | ${{ needs.test_github_action.outputs['output4'] }}"

          if [ "${{ needs.test_github_action.outputs['output1'] }}" == "success" ] && [ "${{ needs.test_github_action.outputs['output2'] }}" == "failure" ] && [ "${{ needs.test_github_action.outputs['output3'] }}" == "failure" ] && [ "${{ needs.test_github_action.outputs['output4'] }}" == "failure" ]; then
            echo "Test succeeded: Actual outcomes match expected outcomes"
            exit 0
          else
            echo "Test failed: Actual outcomes do not match expected outcomes."
            exit 1
          fi
   
